Data_Preparation:
  test_size: 0.2
  random_state: 01

Train:
  Random_Forest:
    n_estimators: 426
    max_depth: 14
    max_features: null
    min_samples_split: 2
    min_samples_leaf: 5
    max_samples: 0.9458861096734634
    n_jobs: -1
  XGBM:
    n_estimators: 913
    learning_rate: 0.012860777628650696
    max_depth: 12
    min_child_weight: 5
    gamma: 0.6039932110732424
    subsample: 0.9259983926052949
    colsample_bytree: 0.9694518217593998
    reg_alpha: 0.3741656346007033
    reg_lambda: 4.478700391560461
    max_bin: 157
    verbosity: 1
    n_jobs: -1